version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO_NAME: coworking-analytics
    IMAGE_TAG: "1.0.1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - cd analytics
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo Build complete. Image pushed to $ECR_URI:$IMAGE_TAG
